language: python

python:
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=. tests/test_api.py
  - flake8 .

services:
  - docker

before_script:
  - docker build -t sistema-matriculas .

after_success:
  - docker run --rm sistema-matriculas pytest tests/test_api.py